menu:
    # Home: /
    # Archive: /archives/
    # About: "http://jeremyfan.name"
    카카오톡 문의: "https://www.wp-talk.com/kakao/"

title: WP-TALK.COM
description: WP-TALK.COM Docs

favicon: /favicon.ico

# Copyright Infomation
# startyear: 2017
